import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar/NavBar";
import BackgroundWrapper from "@/components/BackgroundWrapper/BackgroundWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <BackgroundWrapper>
          <div className="wrapper w-screen h-screen flex flex-col">
            <NavBar/>
            {children}
          </div>
        </BackgroundWrapper>
      </body>
    </html>
  );
}
