import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import NavBar from "@/components/NavBar";
import BackgroundWrapper from "@/components/BackgroundWrapper";
import StoreProvider from "@/components/StoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log(inter.className);
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <BackgroundWrapper>
            <NavBar />
            <main className="text-container pt-24 wrapper w-full overflow-x-hidden">
              {children}
            </main>
          </BackgroundWrapper>
        </StoreProvider>
      </body>
    </html>
  );
}
