import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import NavBar from "@/components/NavBar/NavBar";
import BackgroundWrapper from "@/components/BackgroundWrapper/BackgroundWrapper";
import TranitionProvider from "@/components/TranitionProvider/TranitionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <BackgroundWrapper>
          <TranitionProvider>
            <NavBar />
            {children}
          </TranitionProvider>
        </BackgroundWrapper>
      </body>
    </html>
  );
}
