export const projects = [
  {
    id: 0,
    title: "Codinity Labs",
    desc: "This is a website for a company that provides software development services. It's a responsive and interactive website that showcases the company's services and projects.",
    img: "/assets/images/codinity.jpg",
    link: "https://github.com/Kyryloloshka/CodinityLabs",
    linkGh: "https://github.com/Kyryloloshka/CodinityLabs",
  },
  {
    id: 1,
    title: "Student Council Website",
    desc: "This is a student council website built with Next.js. It allows students to view upcoming events, import schedules to their calendar, join student council, and more.",
    img: "/assets/images/sckpi.png",
    link: "https://sc.kpi.ua/",
    linkGh: "https://github.com/srkpi/sc-kpi-web",
  },
  {
    id: 2,
    title: "3D tic tac toe",
    desc: "Innovative 3D tic tac toe game built with Three.js and Next.js. It's a fun game to play with friends and family.",
    img: "/assets/images/tic-tac-toe.png",
    link: "https://ddd-tic-tac-toe.vercel.app/",
    linkGh: "https://github.com/Kyryloloshka/3D-Tic-Tac-Toe",
  },
  {
    id: 3,
    title: "Communi Chat App",
    desc: "This is a chat application built with Next.js and Firebase. It allows users to chat with friends and family.",
    img: "/assets/images/communi.png",
    link: "https://communi-ochre.vercel.app/",
    linkGh: "https://github.com/Kyryloloshka/Communi",
  },
  {
    id: 4,
    title: "Tohachat App",
    desc: "This is a social media application built with Next.js and Appwrite database. That allows users to post messages and images, and also like and comment on posts, edit their profile, and more.",
    img: "/assets/images/tohachat.png",
    link: "https://tohachat.vercel.app/",
    linkGh: "https://github.com/Kyryloloshka/Tohachat",
  },
  {
    id: 5,
    title: "This Portfolio",
    desc: "This portfolio is built with Next.js, Framer Motion and Gsap. It's a responsive and interactive portfolio that showcases my works and skills.",
    img: "/assets/images/portfolio.png",
    link: "/",
    linkGh: "https://github.com/Kyryloloshka/Halyamov",
  },
];
